# Dependencies
markdown:
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Towards Computer Vision
tagline:          'A friendly programming blog'
description:      'Sharing ideas, learning and discussing computer vision algorithms'
url:              https://abdelrhmanbassiouny.github.io
baseurl:          /

author:
  name:           'Abderlhman Bassiouny'
  url:            https://github.com/AbdelrhmanBassiouny

paginate:         5
