# Dependencies
markdown:
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Towards Computer Vision
tagline:          'A friendly programming blog'
description:      'Sharing ideas and learning about interesting computer vision algorithms'
url:              http://github.com/AbdelrhmanBassiouny
baseurl:          /

author:
  name:           'Abdelrhman Bassiouny'
  url:            http://github.com/AbdelrhmanBassiouny

paginate:         5
